# Generated by Django 4.2.16 on 2024-09-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('terrian', models.CharField(max_length=10)),
                ('fireBreather', models.BooleanField()),
                ('waterBreather', models.BooleanField()),
                ('eyeColor', models.CharField(max_length=10)),
                ('armored', models.BooleanField()),
                ('horns', models.IntegerField()),
                ('fins', models.BooleanField()),
                ('feathers', models.BooleanField()),
                ('wings', models.BooleanField()),
                ('legs', models.IntegerField()),
            ],
        ),
    ]
