# Generated by Django 4.2.16 on 2024-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairesDragonApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragon',
            old_name='terrian',
            new_name='terrain',
        ),
        migrations.AddField(
            model_name='dragon',
            name='url',
            field=models.CharField(default='Forest', max_length=200),
            preserve_default=False,
        ),
    ]
