# Generated by Django 4.2.16 on 2024-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clairesDragonApp', '0002_rename_terrian_dragon_terrain_dragon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='imageKey',
            field=models.CharField(default='img-bPbi2DPYdr4mv6Q0lLUdoZK6', max_length=200),
            preserve_default=False,
        ),
    ]
